package com.study.yang.lifehelper.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "DIARY".
 */
public class Diary implements Serializable{

    private Long id;
    private String title;
    private String content;
    private Long savetime;
    private String deleteType;

    public Diary() {
    }

    public Diary(Long id) {
        this.id = id;
    }

    public Diary(Long id, String title, String content, Long savetime, String deleteType) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.savetime = savetime;
        this.deleteType = deleteType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getSavetime() {
        return savetime;
    }

    public void setSavetime(Long savetime) {
        this.savetime = savetime;
    }

    public String getDeleteType() {
        return deleteType;
    }

    public void setDeleteType(String deleteType) {
        this.deleteType = deleteType;
    }

}
